name: dart_object_extension
description: This plugin extends the functionality of the object class.
version: 0.3.0
homepage: https://github.com/JosephNK/dart_object_extension

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.12.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
