name: dart_object_extension_gen
description: This plugin extends the functionality of the object class.
version: 0.3.0
homepage: https://github.com/JosephNK/dart_object_extension

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^10.0.0
  build: ^4.0.0
  source_gen: ^4.0.1
  dart_object_extension: ^0.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  source_gen_test: ^1.3.2

flutter:
